project(bsq)
set(${PROJECT_NAME}_VENDOR "juspende & alucas-")
set(${PROJECT_NAME}_CONTACT "github.com/SpenderJ/bsq/issues")
set(${PROJECT_NAME}_SUMMARY "bsq - My bsq is faster than yours")
set(${PROJECT_NAME}_MAJOR 0)
set(${PROJECT_NAME}_MINOR 0)
set(${PROJECT_NAME}_PATCH 1)
set(${PROJECT_NAME}_README README.md)
set(${PROJECT_NAME}_LICENSE LICENSE)
